apiVersion: v1
kind: Pod
metadata:
   name: portworx-nfs-static-pod
spec:
  containers:
  - image: nginx
    name: nginx-portworx-static
    volumeMounts:
    - mountPath: /test-portworx-volume
      name: portworx
  volumes:
  - name: portworx
    persistentVolumeClaim:
      claimName: portworx-nfs-static-pvc