apiVersion: v1
kind: PersistentVolume
metadata:
  name: portworx-nfs-static-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  portworxVolume:
    volumeID: 'volumeID'