kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portworx-nfs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: portworx-nfs-static-pv