kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: portworx-proxy-nfs
  volumeMode: Filesystem